# Generated by Django 5.1.7 on 2025-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productrating_productreview_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
